# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - htmlzip
  - pdf
  - epub

conda:
  environment: environment_docs.yml
