name: pmt_docs
channels:
  - esri
  - conda-forge
  - nodefaults
dependencies:
  - python=3.7
  - arcpy
  - arcgis
  - momepy
  - dask
  - geopandas
  - pandas
  - numpy
  - scipy
  - rtree=0.9.4
  - sphinx
  - pip
  - pip:
      - simpledbf
      - censusdata
      - osmnx
      - sphinx-sizzle-theme