name: pmt_dl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - geopandas
  - pandas
  - numpy
  - scipy
  - rtree=0.9.4
  - sphinx
  - pip
  - pip:
      - simpledbf
      - osmnx
